###THE SCHEMA MYSQL
CREATE DATABASE burgers_db;
##USE WILL GRAB THE DB CALLED burgers_db
USE burgers_db;

CREATE TABLE burgers(	
	id int NOT NULL AUTO_INCREMENT,
	burger_name varchar(45) NOT NULL,
	devoured TINYINT(0) DEFAULT false,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
